version: "3.8"

services:
  app:
    container_name: hc-2023-spyder-dev
    image: hc-2023-spyder-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000